-- ============================================================
-- Premier Resources table
-- Date: 2026-05-07
--
-- Creates the premier_resources table for storing gated content
-- (documents, recordings, templates) accessible to Premier members.
--
-- RLS:
--   - Admins: full access (SELECT, INSERT, UPDATE, DELETE)
--   - Premier + Active members: SELECT only
--   - All others: no access
-- ============================================================

create table public.premier_resources (
    id bigint generated by default as identity primary key,
    title text not null,
    description text,
    resource_type text not null check (resource_type in ('document', 'recording', 'template')),
    url text not null,
    is_published boolean not null default true,
    created_by bigint references public.sales(id),
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

alter table public.premier_resources enable row level security;

-- Helper: returns true if the current user's linked contact has Premier tier + Active status
create or replace function public.is_premier_member()
returns boolean
language plpgsql security definer
set search_path to ''
as $$
begin
  return exists (
    select 1
    from public.contacts c
    join public.sales s on c.sales_id = s.id
    where s.user_id = auth.uid()
      and c.membership_tier = 'Premier'
      and c.member_status = 'Active'
  );
end;
$$;

-- Admins: full access
create policy "Premier resources: admin select"
  on public.premier_resources for select to authenticated
  using (public.is_admin());

create policy "Premier resources: admin insert"
  on public.premier_resources for insert to authenticated
  with check (public.is_admin());

create policy "Premier resources: admin update"
  on public.premier_resources for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

create policy "Premier resources: admin delete"
  on public.premier_resources for delete to authenticated
  using (public.is_admin());

-- Premier members: SELECT published resources only
create policy "Premier resources: premier member select"
  on public.premier_resources for select to authenticated
  using (
    is_published = true
    and public.is_premier_member()
  );
